// Fake testimonials, replace with real Google reviews later
export const testimonials = [
  {
    id: 1,
    name: "Marcus T.",
    location: "Pflugerville, TX",
    rating: 5,
    date: "March 2025",
    text: "Tronell and his crew were absolutely phenomenal. They showed up on time, fixed our deck, repaired two doors that wouldn't close properly, and patched a hole in the drywall, all in one visit. Transparent pricing, no surprises. Will definitely call again.",
    service: "Deck Repair & Drywall",
    avatar: "M",
  },
  {
    id: 2,
    name: "Sarah K.",
    location: "Austin, TX",
    rating: 5,
    date: "January 2025",
    text: "I've tried several handyman services in Austin and none of them come close to Anytime Handyman. They responded same day, gave me a clear quote, and the work was flawless. My bathroom remodel looks incredible. Highly recommend!",
    service: "Bathroom Update",
    avatar: "S",
  },
  {
    id: 3,
    name: "David R.",
    location: "Round Rock, TX",
    rating: 5,
    date: "November 2024",
    text: "Signed up for their monthly maintenance plan and it has been one of the best decisions I've made as a homeowner. They catch small issues before they become expensive problems. Peace of mind is worth every penny.",
    service: "Monthly Maintenance Plan",
    avatar: "D",
  },
  {
    id: 4,
    name: "Angela M.",
    location: "Cedar Park, TX",
    rating: 5,
    date: "October 2024",
    text: "Had them install ceiling fans, mount 3 TVs, and fix a leaky faucet. Professional, friendly, and incredibly efficient. They were done in less time than I expected and cleaned up after themselves. 10/10.",
    service: "Fixture Installation & TV Mounting",
    avatar: "A",
  },
  {
    id: 5,
    name: "James L.",
    location: "Georgetown, TX",
    rating: 5,
    date: "August 2024",
    text: "The epoxy garage floor they installed is absolutely stunning. So many neighbors have stopped by to ask who did it. Quality work at a fair price. The team was professional from start to finish.",
    service: "Epoxy Garage Floor",
    avatar: "J",
  },
  {
    id: 6,
    name: "Priya S.",
    location: "Pflugerville, TX",
    rating: 5,
    date: "June 2024",
    text: "Called them for fence repair after a big storm. They came out the next morning, assessed everything, and had it fixed by afternoon. Exactly what 'Anytime' means, they really deliver on that promise.",
    service: "Fence Repair",
    avatar: "P",
  },
];
